---

MODEL:
    THRESHOLD: 0.25
    NAME: "efficientnet-b7"
    NUM_CLASSES: 1
OUTPUT_DIR: "outputs/effnet"
TRAINER:
    LR: 3e-2
    EPOCHS: 25
INPUT:
    TRANSFORM:
        RAND_GAUSS:
            ACTIVE: True
            INTENSITY: 0.35
        LENGTH: 40960
    RECORD_LENGTH: 40960
INFERENCE:
    THRESHOLD: 0.95
...
